version: "3.7"

services:
  bfa_web:
    container_name: bfa_web 
    networks:
      - bfa_netw
    build: 
      context: .
      args:
        - BUILD_DATE=${BUILD_DATE}
        - VCS_REF=${VCS_REF}
        - VERSION=${VERSION}
    ports:
      - "8888:80"
    restart: always

networks:
  bfa_netw:
